SELECT * FROM weile.PUBLIC_USER_INFORMATION MINUS SELECT * FROM VIEW_USER_INFORMATON;
SELECT * FROM VIEW_USER_INFORMATON MINUS SELECT * FROM weile.PUBLIC_USER_INFORMATION;

SELECT * FROM weile.PUBLIC_PHOTO_INFORMATION MINUS SELECT * FROM VIEW_PHOTO_INFORMATON;
SELECT * FROM VIEW_PHOTO_INFORMATON MINUS SELECT * FROM weile.PUBLIC_PHOTO_INFORMATION;

SELECT * FROM weile.PUBLIC_TAG_INFORMATION MINUS SELECT * FROM VIEW_TAG_INFORMATON;
SELECT * FROM VIEW_TAG_INFORMATON MINUS SELECT * FROM weile.PUBLIC_TAG_INFORMATION;

SELECT * FROM weile.PUBLIC_EVENT_INFORMATION MINUS SELECT * FROM VIEW_EVENT_INFORMATON;
SELECT * FROM VIEW_EVENT_INFORMATON MINUS SELECT * FROM weile. PUBLIC_EVENT_INFORMATION;